config:
  token: <%= ENV['CODE_STATS_TOKEN'] %>
  ci: 'CIRCLECI'
  url: <%= ENV['CODE_STATS_URL'] %>
metrics:
  rubycritic:
    name: 'RubyCritic'
    enabled: false
    minimum: 70
    upload_report: true
    report_dir: 'tmp/rubycritic'
    uploader_key: <%= ENV['CODE_STATS_S3_KEY'] %>
    uploader_secret: <%= ENV['CODE_STATS_S3_SECRET_KEY'] %>
    uploader_region: <%= ENV['CODE_STATS_S3_REGION'] %>
    uploader_bucket: <%= ENV['CODE_STATS_S3_BUCKET'] %>
  simplecov:
    name: 'SimpleCov'
    enabled: false
    minimum: 70
  slather:
    name: 'Slather'
    enabled: false
    minimum: 70
    upload_report: true
    report_dir: 'coverage'
    uploader_key: <%= ENV['CODE_STATS_S3_KEY'] %>
    uploader_secret: <%= ENV['CODE_STATS_S3_SECRET_KEY'] %>
    uploader_region: <%= ENV['CODE_STATS_S3_REGION'] %>
    uploader_bucket: <%= ENV['CODE_STATS_S3_BUCKET'] %>
